import { createContext, useCallback, useContext, useEffect, useState, type ReactNode } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import type { LocalAccount } from '@/src/domain/models';
import { accountStorage } from '@/src/storage/accounts';
import { providerRegistry } from '@/src/providers/registry';
import { invalidateAccountQueries } from '@/src/services/accounts';
export type AccountSummary = Pick<LocalAccount, 'id' | 'revision' | 'label' | 'providerId' | 'login'>;
interface Value { accounts: AccountSummary[]; active?: AccountSummary; loading: boolean; error?: string; reload: () => Promise<void>; switchAccount: (id: string) => Promise<void>; saveAccount: (account: LocalAccount) => Promise<void>; removeAccount: (id: string) => Promise<void>; }
const Context = createContext<Value | null>(null);
export function AccountsProvider({ children }: { children: ReactNode }) { const queryClient = useQueryClient(); const [accounts, setAccounts] = useState<AccountSummary[]>([]); const [activeId, setActiveId] = useState<string>(); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>(); const reload = useCallback(async () => { try { const values = await accountStorage.list(); const stored = await accountStorage.getActive(); const selected = values.find((account) => account.id === stored)?.id ?? values[0]?.id; if (selected) await accountStorage.setActive(selected); setAccounts(values.map(({ id, revision, label, providerId, login }) => ({ id, revision, label, providerId, login }))); setActiveId(selected); setError(undefined); } catch { setError('无法读取本地账号，请重试。原有数据未清除。'); } finally { setLoading(false); } }, []); useEffect(() => { void accountStorage.migrate(providerRegistry.list().map((provider) => provider.metadata.id)).then(reload).catch(() => { setError('旧账号迁移失败，请重试。原有数据未清除。'); setLoading(false); }); }, [reload]); async function switchAccount(id: string) { if (!await accountStorage.load(id)) throw new Error('账号已删除'); await accountStorage.setActive(id); setActiveId(id); } async function saveAccount(account: LocalAccount) { await accountStorage.save(account); invalidateAccountQueries(queryClient, account.id); await accountStorage.setActive(account.id); await reload(); } async function removeAccount(id: string) { const account = await accountStorage.load(id); if (account?.session) { try { await providerRegistry.get(account.providerId)?.logout(account.session); } catch { /* Cookie 清理失败不阻断本地账号删除。 */ } } await accountStorage.remove(id); invalidateAccountQueries(queryClient, id); await reload(); } return <Context.Provider value={{ accounts, active: accounts.find((account) => account.id === activeId), loading, error, reload, switchAccount, saveAccount, removeAccount }}>{children}</Context.Provider>; }
export function useAccounts() { const value = useContext(Context); if (!value) throw new Error('AccountsProvider is required'); return value; }
