/**
 * 由 tools/generate-theme-palettes.mjs 用 @material/material-color-utilities 预生成的
 * 预设主题色调色板（浅色/深色）；勿手改。运行环境说明见脚本头部注释。
 * 键为大写种子色（#RRGGBB）。
 */
export interface PaletteScheme {
  primary: string; onPrimary: string; primaryContainer: string; onPrimaryContainer: string;
  secondary: string; onSecondary: string; secondaryContainer: string; onSecondaryContainer: string;
  tertiary: string; onTertiary: string; tertiaryContainer: string; onTertiaryContainer: string;
  background: string; onBackground: string;
  surface: string; onSurface: string;
  surfaceVariant: string; onSurfaceVariant: string;
  outline: string; outlineVariant: string;
  inverseSurface: string; inverseOnSurface: string; inversePrimary: string;
}

export const presetPalettes: Record<string, { light: PaletteScheme; dark: PaletteScheme }> = {
  /** 蓝 */
  '#0B57D0': {
    light: {
      "primary": "#0856cf",
      "onPrimary": "#ffffff",
      "primaryContainer": "#dae2ff",
      "onPrimaryContainer": "#001847",
      "secondary": "#585e71",
      "onSecondary": "#ffffff",
      "secondaryContainer": "#dce2f9",
      "onSecondaryContainer": "#151b2c",
      "tertiary": "#735471",
      "onTertiary": "#ffffff",
      "tertiaryContainer": "#fed7f9",
      "onTertiaryContainer": "#2b122b",
      "background": "#fefbff",
      "onBackground": "#1b1b1f",
      "surface": "#fefbff",
      "onSurface": "#1b1b1f",
      "surfaceVariant": "#e1e2ec",
      "onSurfaceVariant": "#45464f",
      "outline": "#757780",
      "outlineVariant": "#c5c6d0",
      "inverseSurface": "#303034",
      "inverseOnSurface": "#f2f0f4",
      "inversePrimary": "#b2c5ff"
    },
    dark: {
      "primary": "#b2c5ff",
      "onPrimary": "#002b72",
      "primaryContainer": "#0040a1",
      "onPrimaryContainer": "#dae2ff",
      "secondary": "#c0c6dd",
      "onSecondary": "#2a3042",
      "secondaryContainer": "#404659",
      "onSecondaryContainer": "#dce2f9",
      "tertiary": "#e1bbdd",
      "onTertiary": "#412741",
      "tertiaryContainer": "#5a3d59",
      "onTertiaryContainer": "#fed7f9",
      "background": "#1b1b1f",
      "onBackground": "#e4e2e6",
      "surface": "#1b1b1f",
      "onSurface": "#e4e2e6",
      "surfaceVariant": "#45464f",
      "onSurfaceVariant": "#c5c6d0",
      "outline": "#8f909a",
      "outlineVariant": "#45464f",
      "inverseSurface": "#e4e2e6",
      "inverseOnSurface": "#1b1b1f",
      "inversePrimary": "#0856cf"
    },
  },
  /** 绿 */
  '#2E7D32': {
    light: {
      "primary": "#1b6d24",
      "onPrimary": "#ffffff",
      "primaryContainer": "#a3f69c",
      "onPrimaryContainer": "#002204",
      "secondary": "#52634f",
      "onSecondary": "#ffffff",
      "secondaryContainer": "#d6e8ce",
      "onSecondaryContainer": "#111f0f",
      "tertiary": "#38656a",
      "onTertiary": "#ffffff",
      "tertiaryContainer": "#bcebf0",
      "onTertiaryContainer": "#002023",
      "background": "#fcfdf6",
      "onBackground": "#1a1c19",
      "surface": "#fcfdf6",
      "onSurface": "#1a1c19",
      "surfaceVariant": "#dee5d8",
      "onSurfaceVariant": "#424940",
      "outline": "#72796f",
      "outlineVariant": "#c2c9bd",
      "inverseSurface": "#2f312d",
      "inverseOnSurface": "#f0f1eb",
      "inversePrimary": "#88d982"
    },
    dark: {
      "primary": "#88d982",
      "onPrimary": "#003909",
      "primaryContainer": "#005312",
      "onPrimaryContainer": "#a3f69c",
      "secondary": "#baccb3",
      "onSecondary": "#253423",
      "secondaryContainer": "#3b4b38",
      "onSecondaryContainer": "#d6e8ce",
      "tertiary": "#a0cfd4",
      "onTertiary": "#00363b",
      "tertiaryContainer": "#1f4d52",
      "onTertiaryContainer": "#bcebf0",
      "background": "#1a1c19",
      "onBackground": "#e2e3dd",
      "surface": "#1a1c19",
      "onSurface": "#e2e3dd",
      "surfaceVariant": "#424940",
      "onSurfaceVariant": "#c2c9bd",
      "outline": "#8c9388",
      "outlineVariant": "#424940",
      "inverseSurface": "#e2e3dd",
      "inverseOnSurface": "#1a1c19",
      "inversePrimary": "#1b6d24"
    },
  },
  /** 黄 */
  '#F9AB00': {
    light: {
      "primary": "#805600",
      "onPrimary": "#ffffff",
      "primaryContainer": "#ffddb0",
      "onPrimaryContainer": "#281800",
      "secondary": "#6f5b40",
      "onSecondary": "#ffffff",
      "secondaryContainer": "#f9debb",
      "onSecondaryContainer": "#261904",
      "tertiary": "#506441",
      "onTertiary": "#ffffff",
      "tertiaryContainer": "#d2eabd",
      "onTertiaryContainer": "#0e2004",
      "background": "#fffbff",
      "onBackground": "#1f1b16",
      "surface": "#fffbff",
      "onSurface": "#1f1b16",
      "surfaceVariant": "#efe0cf",
      "onSurfaceVariant": "#4f4539",
      "outline": "#817567",
      "outlineVariant": "#d2c4b4",
      "inverseSurface": "#34302a",
      "inverseOnSurface": "#f9efe7",
      "inversePrimary": "#ffba45"
    },
    dark: {
      "primary": "#ffba45",
      "onPrimary": "#442c00",
      "primaryContainer": "#614000",
      "onPrimaryContainer": "#ffddb0",
      "secondary": "#dcc3a1",
      "onSecondary": "#3d2e16",
      "secondaryContainer": "#55442a",
      "onSecondaryContainer": "#f9debb",
      "tertiary": "#b6cea3",
      "onTertiary": "#233517",
      "tertiaryContainer": "#394c2b",
      "onTertiaryContainer": "#d2eabd",
      "background": "#1f1b16",
      "onBackground": "#eae1d9",
      "surface": "#1f1b16",
      "onSurface": "#eae1d9",
      "surfaceVariant": "#4f4539",
      "onSurfaceVariant": "#d2c4b4",
      "outline": "#9b8f80",
      "outlineVariant": "#4f4539",
      "inverseSurface": "#eae1d9",
      "inverseOnSurface": "#1f1b16",
      "inversePrimary": "#805600"
    },
  },
  /** 红 */
  '#C62828': {
    light: {
      "primary": "#b91d20",
      "onPrimary": "#ffffff",
      "primaryContainer": "#ffdad6",
      "onPrimaryContainer": "#410003",
      "secondary": "#775653",
      "onSecondary": "#ffffff",
      "secondaryContainer": "#ffdad6",
      "onSecondaryContainer": "#2c1513",
      "tertiary": "#725b2e",
      "onTertiary": "#ffffff",
      "tertiaryContainer": "#fedea6",
      "onTertiaryContainer": "#261900",
      "background": "#fffbff",
      "onBackground": "#201a19",
      "surface": "#fffbff",
      "onSurface": "#201a19",
      "surfaceVariant": "#f5dddb",
      "onSurfaceVariant": "#534341",
      "outline": "#857371",
      "outlineVariant": "#d8c2bf",
      "inverseSurface": "#362f2e",
      "inverseOnSurface": "#fbeeec",
      "inversePrimary": "#ffb4ac"
    },
    dark: {
      "primary": "#ffb4ac",
      "onPrimary": "#690007",
      "primaryContainer": "#93000e",
      "onPrimaryContainer": "#ffdad6",
      "secondary": "#e7bdb8",
      "onSecondary": "#442927",
      "secondaryContainer": "#5d3f3c",
      "onSecondaryContainer": "#ffdad6",
      "tertiary": "#e0c38c",
      "onTertiary": "#3f2d04",
      "tertiaryContainer": "#584419",
      "onTertiaryContainer": "#fedea6",
      "background": "#201a19",
      "onBackground": "#ede0de",
      "surface": "#201a19",
      "onSurface": "#ede0de",
      "surfaceVariant": "#534341",
      "onSurfaceVariant": "#d8c2bf",
      "outline": "#a08c8a",
      "outlineVariant": "#534341",
      "inverseSurface": "#ede0de",
      "inverseOnSurface": "#201a19",
      "inversePrimary": "#b91d20"
    },
  }
};
